<?php

return array(
    'gallery_templates' => array(
        'title' => __( 'PRO Gallery Templates','foogallery' ),
        'desc' => __( '3 more advanced gallery templates to help you showcase your photography, including Slider PRO, Grid PRO and Polaroid PRO.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/gallery-templates/',
        'utm_content' => 'gallery_templates',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-templates.png',
        'plan' => FOOGALLERY_PRO_PLAN_STARTER,
        'plans' => array( FOOGALLERY_PRO_PLAN_STARTER, FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'hover_effects' => array(
        'title' => __( 'Animated Hover Effect Presets','foogallery' ),
        'desc' => __( 'Choose from 11 animated hover effect presets, to add that professional and elegant look to your galleries.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/hover-presets/',
        'utm_content' => 'hover_presets',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-presets.png',
        'plan' => FOOGALLERY_PRO_PLAN_STARTER,
        'plans' => array( FOOGALLERY_PRO_PLAN_STARTER, FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'image_filter_effects' => array(
        'title' => __( 'Image Filter Effects','foogallery' ),
        'desc' => __( 'Mage your galleries pop, by adding one of 12 image filter effects to your thumbnails, just like you can do with Instagram. Make your galleries stand out from the competition!', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/filter-effects/',
        'utm_content' => 'filter_effects',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-effects.png',
        'plan' => FOOGALLERY_PRO_PLAN_STARTER,
        'plans' => array( FOOGALLERY_PRO_PLAN_STARTER, FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'video' => array(
        'title' => __( 'Video Galleries','foogallery' ),
        'desc' => __( 'Showcase your videos! Create amazing video galleries by importing videos from YouTube, Vimeo and other sources. Also create galleries from self-hosted videos that you have uploaded to your media library. You can also create mixed galleries with both videos and images.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/video-gallery/',
        'utm_content' => 'videos',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-videos.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'filtering' => array(
        'title' => __( 'Multi-Level Tag Filtering','foogallery' ),
        'desc' => __( 'Add tags or categories to your images or videos, and then allow your visitors to filter your gallery. Distinguish between your tags by showing count, or changing the size or opacity. You can also setup multi-level filtering!', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/filtering/',
        'utm_content' => 'filtering',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-filtering.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'search' => array(
        'title' => __( 'Gallery Search','foogallery' ),
        'desc' => __( 'Add a search input to your gallery to allow your visitors to search the gallery by the caption or tags.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/filtering/#search',
        'utm_content' => 'search-filtering',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-search-filter.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'pagination' => array(
        'title' => __( 'Advanced Pagination','foogallery' ),
        'desc' => __( 'Add more advanced types of pagination to your galleries, including page numbering and the popular "Infinite Scroll" and "Load More" variations. Paging is a very useful for larger galleries, as it means your visitors do not need to load the entire gallery all at once.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/pagination/',
        'utm_content' => 'pagination',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-pagination.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'dynamic_galleries' => array(
        'title' => __( 'Dynamic Galleries','foogallery' ),
        'desc' => __( 'Create dynamic galleries from other sources, including Tags, Categories, Server Folders, Adobe Lightroom or a Post Query.', 'foogallery' ),
        'link' => 'https://fooplugins.com/load-galleries-from-other-sources/',
        'utm_content' => 'datasources',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-datasources2.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'custom_captions' => array(
        'title' => __( 'Custom Captions','foogallery' ),
        'desc' => __( 'Customize your gallery captions, by building dynamic captions using HTML and pre-defined placeholders. Integrates with popular solutions like ACF and Pods for unlimited possibilities.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/custom-captions/',
        'utm_content' => 'captions',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-captions.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'exif' => array(
        'title' => __( 'EXIF Metadata','foogallery' ),
        'desc' => __( 'Show image metadata within your galleries. A must-have for professional photographers wanting to showcase specific metadata about each image.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/exif-data/',
        'utm_content' => 'exif',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-exif.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'bulk_copy' => array(
        'title' => __( 'Bulk Copy Gallery Settings','foogallery' ),
        'desc' => __( 'Copy settings from one gallery to other galleries in bulk.', 'foogallery' ),
        'link' => 'https://fooplugins.com/bulk-copy-foogallery-pro/',
        'utm_content' => 'bulk_copy_settings',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-bulk-copy-settings.png',
        'plan' => FOOGALLERY_PRO_PLAN_EXPERT,
        'plans' => array( FOOGALLERY_PRO_PLAN_EXPERT, FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'product_datasource' => array(
        'title' => __( 'WooCommerce Product Datasource','foogallery' ),
        'desc' => __( 'Create a dynamic product gallery from your WooCommerce products. You can filter and limit the products shown.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/',
        'utm_content' => 'cta_buttons',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-woocommerce-datasource.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'master_product' => array(
        'title' => __( 'Sell Images With A Master Product','foogallery' ),
        'desc' => __( 'Create a single "Master Product" with variations and link it to all the images in your gallery. This means you can start selling your image just like a stock photo website!', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/#master-product',
        'utm_content' => 'product_gallery',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-sell-images-master-product.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'product_gallery' => array(
        'title' => __( 'Product Gallery Template','foogallery' ),
        'desc' => __( 'We created a new gallery template specifically for showcasing products, with all the default settings you need to take the most advantage of the commerce features.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/#product-gallery',
        'utm_content' => 'product_gallery',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-product-gallery.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'protection' => array(
        'title' => __( 'Watermarking &amp; Protection','foogallery' ),
        'desc' => __( 'Protect your images by not allowing visitors to right click, and also by adding watermarks to images in your galleries. Beautiful looking repeating watermarks are built-in, or use your own custom image.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/photo-watermark/',
        'utm_content' => 'protection',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-watermarking.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'lightbox_product_info' => array(
        'title' => __( 'Lightbox Product Info','foogallery' ),
        'desc' => __( 'Our lightbox integrates with WooCommerce, to show product information, including listing all variations and add to cart buttons.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/#product-variations',
        'utm_content' => 'product_info_lightbox',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-product-info-lightbox.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'cta_buttons' => array(
        'title' => __( 'CTA Buttons','foogallery' ),
        'desc' => __( 'Add Call-to-Action buttons to your gallery images or videos. You can link to product pages or allow visitors to add to cart.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/#cta-buttons',
        'utm_content' => 'cta_buttons',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-buttons.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'sales_ribbons' => array(
        'title' => __( 'Sales Ribbons','foogallery' ),
        'desc' => __( 'Add attention-grabbing ribbons to your images to highlight sales or special offers, to increase conversions.', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/#sales-ribbons',
        'utm_content' => 'cta_ribbons',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-ribbons.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'gallery_blueprints' => array(
        'title' => __( 'Gallery Blueprints','foogallery' ),
        'desc' => __( 'Tired of copying settings from one gallery to the next? You will love our Gallery Blueprint feature! Setup a blueprint so that multiple galleries can adopt the same settings and appearance.', 'foogallery' ),
        'link' => 'https://fooplugins.com/documentation/foogallery/pro-commerce/use-master-gallery/',
        'utm_content' => 'cta_gallery_blueprints',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-master-galleries.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'whitelabeling' => array(
        'title' => __( 'White Labeling','foogallery' ),
        'desc' => __( 'Rebrand FooGallery to whatever you like for your clients. Move or hide menu items too. Ideal for freelancers and agencies.', 'foogallery' ),
        'link' => 'https://fooplugins.com/documentation/foogallery/pro-commerce/white-labeling/',
        'utm_content' => 'cta_white_labeling',
        'link_text' => __( 'Learn More','foogallery' ),
        'image' => 'https://assets.fooplugins.com/foogallery/plugin/foogallery-admin-help-pro-white-labeling.png',
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
    ),
    'ecommerce' => array(
        'title' => __( 'Ecommerce','foogallery' ),
        'desc' => __( 'Extend the functionality of your gallery with seamless WooCommerce integration. Load all your products into a product gallery with call-to-action buttons and sales ribbons. Or create a single "master product" and make money selling your gallery images!', 'foogallery' ),
        'link' => 'https://fooplugins.com/foogallery-wordpress-gallery-plugin/woocommerce-integration/',
        'utm_content' => 'cta_ecommerce',
        'link_text' => __( 'Learn More','foogallery' ),
        'plan' => FOOGALLERY_PRO_PLAN_COMMERCE,
        'plans' => array( FOOGALLERY_PRO_PLAN_COMMERCE ),
        'hide_from_help' => true
    )
);