[
	{
		"slug": "albums",
		"class": "FooGallery_Albums_Extension",
		"title": "Albums",
		"categories": ["Featured" , "Free"],
		"description": "Group your galleries into albums. Boom!",
		"html": "Group your galleries into albums. Boom!",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/extensions/albums/foogallery-albums.png",
		"tags": ["functionality"],
		"source": "bundled",
		"activated_by_default": false,
		"css_class": "coming_soon"
	},
	{
		"slug": "default_templates",
		"class": "FooGallery_Default_Templates_Extension",
		"categories": ["Featured" , "Free"],
		"title": "Default Templates",
		"description": "The bundled gallery templates.",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["template"],
		"source": "bundled",
		"activated_by_default": true
	},
	{
		"slug": "foobox-image-lightbox",
		"class": "Foobox_Free_FooGallery_Extension",
		"categories": ["Featured" , "Free"],
		"file": "foobox-free.php",
		"title": "FooBox FREE",
		"description": "The best lightbox for WordPress. Free",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["lightbox"],
		"source": "repo",
		"activated_by_default": false
	},
	{
		"slug": "foobox",
		"class": "Foobox_FooGallery_Extension",
		"categories": ["Featured" , "Premium"],
		"file": "foobox1.php",
		"title": "FooBox PRO",
		"description": "The best lightbox for WordPress just got even better!",
		"price": "$27",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["premium", "lightbox"],
		"source": "fooplugins",
		"activated_by_default": false,
		"download_button": {
			"text": "Buy - $27",
			"target": "_blank",
			"href": "http://fooplugins.com/plugins/foobox",
			"confirm": false
		}
	},
	{
		"slug": "media_menu",
		"class": "FooGallery_Media_Menu_Extension",
		"categories": ["Free"],
		"file": "foogallery-media-menu.php",
		"title": "Use Media Menu",
		"description": "Move FooGallery menu items underneath the Media menu rather",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["admin"],
		"source": "external"
	},
	{
		"slug": "awesomesauce",
		"class": "FooGallery_Awesomesauce",
		"categories": ["Free"],
		"file": "foogallery-awesomesauce.php",
		"title": "Awesomesauce",
		"description": "I am not sure what this does, but its awesome!",
		"author": "Bongo Muffin",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["awesome", "template"],
		"source": "external"
	},
	{
		"slug": "nextgen",
		"class": "FooGallery_Nextgen_Importer_Extension",
		"categories": ["Premium"],
		"title": "NextGen Importer",
		"description": "Imports all your existing NextGen galleries and albums",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["tools"],
		"source": "bundled"
	},
	{
		"slug": "admin-bookmarks",
		"class": "AdminBookmarks",
		"categories": ["Free"],
		"file": "admin-bookmarks.php",
		"title": "Admin Bookmarks",
		"description": "Imports all your existing NextGen galleries and albums",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"tags": ["test"],
		"source": "github",
		"download_link": "https://github.com/bradvin/wordpress-admin-bookmarks/archive/master.zip"
	},
	{
		"slug": "social-wiggle",
		"class": "socialwiggle",
		"categories": ["Free"],
		"file": "socialwiggle.php",
		"title": "socialwiggle",
		"description": "Imports all your existing NextGen galleries and albums",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assetts/extension_bg.png",
		"source": "repo"
	}
]
