[
	{
		"slug": "default_templates",
		"class": "FooGallery_Default_Templates_Extension",
		"categories": ["Featured" , "Free"],
		"title": "Default Templates",
		"description": "The bundled gallery templates.",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["template"],
		"source": "bundled",
		"activated_by_default": true
	},
	{
		"slug": "albums",
		"class": "FooGallery_Albums_Extension",
		"title": "Albums",
		"categories": ["Featured" , "Free"],
		"description": "Group your galleries into albums. Boom!",
		"html": "Group your galleries into albums. Boom!",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/extensions/albums/foogallery-albums.png",
		"tags": ["functionality"],
		"source": "bundled",
		"css_class": "coming_soon"
	},
	{
		"slug": "media_categories",
		"class": "FooGallery_Media_Categories_Extension",
		"categories": ["Featured" , "Free"],
		"title": "Media Categories",
		"description": "Categorize Your Media.",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["functionality"],
		"source": "bundled"
	},
	{
		"slug": "foobox-image-lightbox",
		"class": "FooGallery_FooBox_Free_Extension",
		"categories": ["Featured" , "Free"],
		"file": "foobox-free.php",
		"title": "FooBox FREE",
		"description": "The best lightbox for WordPress. Free",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["lightbox"],
		"source": "repo",
		"activated_by_default": true,
		"minimum_version": "1.0.2.1"
	},
	{
		"slug": "foobox",
		"class": "FooGallery_FooBox_Extension",
		"categories": ["Featured" , "Premium"],
		"file": "foobox.php",
		"title": "FooBox PRO",
		"description": "The best lightbox for WordPress just got even better!",
		"price": "$27",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["premium", "lightbox"],
		"source": "fooplugins",
		"download_button": {
			"text": "Buy - $27",
			"target": "_blank",
			"href": "http://fooplugins.com/plugins/foobox",
			"confirm": false
		},
		"activated_by_default": true,
		"minimum_version": "2.3.2"
	},
	{
		"slug": "polaroid_template",
		"class": "FooGallery_Polaroid_Template_Extension",
		"categories": ["Featured" , "Free"],
		"file": "foogallery-polaroid-template.php",
		"title": "Polaroid Template",
		"description": "A cool retro Polaroid gallery layout",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["template"],
		"source": "github",
		"download_link": "https://github.com/fooplugins/foogallery-polaroid-template/archive/master.zip"
	},
	{
		"slug": "nextgen",
		"class": "FooGallery_Nextgen_Gallery_Importer_Extension",
		"categories": ["Free"],
		"title": "NextGen Importer",
		"description": "Imports all your existing NextGen galleries",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["tools"],
		"source": "bundled"
	},
	{
		"slug": "media_menu",
		"class": "FooGallery_Media_Menu_Extension",
		"categories": ["Free"],
		"file": "foogallery-media-menu.php",
		"title": "Use Media Menu",
		"description": "Move FooGallery menu items underneath the Media menu rather",
		"author": "FooPlugins",
		"author_url": "http://fooplugins.com",
		"thumbnail": "/assets/extension_bg.png",
		"tags": ["admin"],
		"source": "github",
		"download_link": "https://github.com/fooplugins/foogallery-media-menu/archive/master.zip"
	}
]
